spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/quiz
    username: root
    password: abc123
    dbcp2:
      validation-query: select 1
server:
  port: 8080
mybatis:
  type-aliases-package: com.niit.quiz.entity
  mapper-locations: classpath:/resources/mapper/*.xml